// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2GyyV1uN4xbnqKtJ7pjrQU
// Component: AO9jTWCBi4k
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header3 from "../../Header3"; // plasmic-import: iGqVXRH7Uc/component
import Header2 from "../../Header2"; // plasmic-import: ymsmsqowiD_hX8/component
import ProductCard from "../../ProductCard"; // plasmic-import: 1xV2-KiYepMuGB/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: QbeVAXYyw48xV0/component
import BlogPost from "../../BlogPost"; // plasmic-import: q_LjUx71MsqHbO/component
import Footer from "../../Footer"; // plasmic-import: GewF2Qmnx2xftX/component
import { useScreenVariants as useScreenVariantscf27W7HxUbhqT } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: -CF27w7hxUbhqT/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_e_commerce.module.css"; // plasmic-import: 2GyyV1uN4xbnqKtJ7pjrQU/projectcss
import sty from "./PlasmicProdottoBibita.module.css"; // plasmic-import: AO9jTWCBi4k/css
import LeftArrowSvgrepoComsvgIcon from "./icons/PlasmicIcon__LeftArrowSvgrepoComsvg"; // plasmic-import: BLG2WTl0koydmQ/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: Z9yWUb_XEPOXSj/icon
import header5JpgVk99NncPi5Mx8 from "./images/header5Jpg.jpg"; // plasmic-import: Vk99NNC-Pi5MX8/picture
import plant6LgwebpGl4TZ2Ww7BvxJa from "./images/plant6Lgwebp.webp"; // plasmic-import: GL4tZ2WW7BvxJA/picture
import galinaNMiziNqvJx5MUnsplashjpgEcSqGTgu0W52S from "./images/galinaNMiziNqvJx5MUnsplashjpg.jpg"; // plasmic-import: EcSqG-tgu0W52s/picture
import igorSonFvPxCqgtwcUnsplashjpgIrMvGDzufn8Kk from "./images/igorSonFvPxCqgtwcUnsplashjpg.jpg"; // plasmic-import: IrMvG_dzufn8Kk/picture
import scottWebbORwRlTgBrPoUnsplashjpgP2BhvYxT2EpXaQ from "./images/scottWebbORwRlTgBrPoUnsplashjpg.jpg"; // plasmic-import: p2BhvYxT2EpXaQ/picture
import freddieMarriageUcfKyTanLuUnsplashjpgSug2Aysmy4PT9 from "./images/freddieMarriageUcfKyTanLuUnsplashjpg.jpg"; // plasmic-import: SUG2aysmy4P-T9/picture
import f2NTxTx2MaIc83Th from "./images/f2.jpg"; // plasmic-import: NTxTX2MaIC83Th/picture
import f3QkcmvqYxHP4IK from "./images/f3.jpg"; // plasmic-import: qkcmvqYx_hP4iK/picture
import f4SaIjz82E8CVBx from "./images/f4.jpg"; // plasmic-import: saIjz82e8cV-bx/picture
import b14B1JYr2A7Rzllu from "./images/b1.jpg"; // plasmic-import: 4B1jYr2a7RZLLU/picture
import b2W7N7NGOmbXw1KV from "./images/b2.jpg"; // plasmic-import: W7N7nGOmbXw1kV/picture
import b3EKschWy364XeXy from "./images/b3.jpg"; // plasmic-import: eKschWY364XeXY/picture
import imageNRu8G82XNgF0Pk from "./images/image.png"; // plasmic-import: nRU8g82xNgF0PK/picture
import kappaTrboBxmt9M7Ie5 from "./images/kappa.png"; // plasmic-import: TrboBXMT9m7IE5/picture
import lacosteTEWbuNfm5Ff8Xp from "./images/lacoste.png"; // plasmic-import: tEWbuNfm5Ff8Xp/picture
import levisXnOQSlkr9SjGe from "./images/levis.png"; // plasmic-import: xnO_qSlkr9SjGE/picture
import plant6JpgSmvOu1Xxq5VnGt from "./images/plant6Jpg.png"; // plasmic-import: SmvOU1XXQ5VnGt/picture
import plant1Jpg24LuZtbCwp7W2 from "./images/plant1Jpg.png"; // plasmic-import: 24LuZtbCWP7-w2/picture
import plant7JpgYuSlZZhiiBuc0 from "./images/plant7Jpg.png"; // plasmic-import: YuSl_ZZhiiBuc0/picture
import plant5JpgBQJxNrXugOtY from "./images/plant5Jpg.png"; // plasmic-import: bQJx_NrXugOtY_/picture
import plant41JpgRLnicAZhoI7Gtg from "./images/plant41Jpg.png"; // plasmic-import: RLnicAZhoI7Gtg/picture
import plant31JpgRWGlkbLwKqsXk2 from "./images/plant31Jpg.png"; // plasmic-import: rWGlkbLWKqsXk2/picture
import plant9Webp3TPkYmbEMcCrq from "./images/plant9Webp.webp"; // plasmic-import: _3tPkYmbEMcCrq/picture
import plant2WebpXdOep6UpMySuvS from "./images/plant2Webp.webp"; // plasmic-import: xdOEP6UpMySuvS/picture

export const PlasmicProdottoBibita__VariantProps = new Array();

export const PlasmicProdottoBibita__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicProdottoBibita__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      }
    ],

    [$props, $ctx]
  );

  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantscf27W7HxUbhqT()
  });
  return (
    <p.PlasmicPageGuard
      minRole={null}
      appId={"2GyyV1uN4xbnqKtJ7pjrQU"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={true}
    >
      <React.Fragment>
        <div className={projectcss.plasmic_page_wrapper}>
          <div
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              plasmic_library_plasmic_color_type_css.plasmic_tokens,
              sty.root
            )}
          >
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__v9RDn)}>
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xrmt)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobile")
                        ? true
                        : true
                    ) ? (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__nWoc6)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"35%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: header5JpgVk99NncPi5Mx8,
                          fullWidth: 502,
                          fullHeight: 872,
                          aspectRatio: undefined
                        }}
                      />
                    ) : null}
                    <Header3
                      data-plasmic-name={"header3"}
                      data-plasmic-override={overrides.header3}
                      className={classNames("__wab_instance", sty.header3)}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__tarcB)}
                    >
                      {(
                        hasVariant(globalVariants, "screen", "mobile")
                          ? true
                          : true
                      ) ? (
                        <p.Stack
                          as={"a"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link__riDu
                          )}
                        >
                          <LeftArrowSvgrepoComsvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mFeZo
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__u5DV8
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobile")
                              ? "see all products"
                              : "HOME"}
                          </div>
                        </p.Stack>
                      ) : null}
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"foreground2"}
                        data-plasmic-override={overrides.foreground2}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.foreground2)}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.columns__xhReB
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column___1Aqo
                            )}
                          >
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__isP8A)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: plant6LgwebpGl4TZ2Ww7BvxJa,
                                fullWidth: 900,
                                fullHeight: 900,
                                aspectRatio: undefined
                              }}
                            />
                          </div>
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.column__xLvPg
                            )}
                          >
                            <h3
                              data-plasmic-name={"h3"}
                              data-plasmic-override={overrides.h3}
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3
                              )}
                            >
                              {"Fico"}
                            </h3>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__mtIdB
                              )}
                            >
                              {"PIANTE"}
                            </div>
                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5___6Wdh2
                              )}
                            >
                              {"$10.00"}
                            </h5>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__w37Yd
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__lYlZl
                                )}
                              >
                                {"Ficus"}
                              </div>
                              {(
                                hasVariant(globalVariants, "screen", "mobile")
                                  ? true
                                  : true
                              ) ? (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__z1QE
                                  )}
                                >
                                  {(
                                    hasVariant(
                                      globalVariants,
                                      "screen",
                                      "mobile"
                                    )
                                      ? true
                                      : true
                                  ) ? (
                                    <p.Stack
                                      as={"a"}
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.a,
                                        sty.link___7TWpZ
                                      )}
                                    >
                                      <Icon3Icon
                                        className={classNames(
                                          projectcss.all,
                                          sty.svg___3WTrQ
                                        )}
                                        role={"img"}
                                      />

                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__gWfoq
                                        )}
                                      >
                                        {hasVariant(
                                          globalVariants,
                                          "screen",
                                          "mobile"
                                        )
                                          ? "Discover"
                                          : "Aggiungi al carrello"}
                                      </div>
                                    </p.Stack>
                                  ) : null}
                                </div>
                              ) : null}
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>
                    </div>
                  </div>
                ) : null}
              </div>
            ) : null}
            {true ? (
              <div
                data-plasmic-name={"header"}
                data-plasmic-override={overrides.header}
                className={classNames(projectcss.all, sty.header)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__blInz)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__oe9Di)}
                  >
                    {true ? (
                      <Header2
                        data-plasmic-name={"header2"}
                        data-plasmic-override={overrides.header2}
                        className={classNames("__wab_instance", sty.header2)}
                      />
                    ) : null}
                  </div>
                </p.Stack>
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ss4MD)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__wtX6P
                      )}
                    >
                      {"Top Collections"}
                    </h2>
                  </div>
                ) : null}
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__qbwSg)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__yh4H2)}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__sjNn3
                        )}
                        image={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__se83D)}
                            displayHeight={"100%"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            src={{
                              src: galinaNMiziNqvJx5MUnsplashjpgEcSqGTgu0W52S,
                              fullWidth: 1920,
                              fullHeight: 1278,
                              aspectRatio: undefined
                            }}
                          />
                        }
                        onSale={true}
                        price={"$65.00"}
                        title={"Product"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__rmXzI)}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__a1NfJ
                        )}
                        image={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__ssK9)}
                            displayHeight={"100%"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            src={{
                              src: igorSonFvPxCqgtwcUnsplashjpgIrMvGDzufn8Kk,
                              fullWidth: 640,
                              fullHeight: 481,
                              aspectRatio: undefined
                            }}
                          />
                        }
                        onSale={true}
                        price={"$80.00"}
                        title={"Product"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__gMt6F)}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__f0Qz
                        )}
                        image={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__nha5R)}
                            displayHeight={"100%"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            src={{
                              src: scottWebbORwRlTgBrPoUnsplashjpgP2BhvYxT2EpXaQ,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined
                            }}
                          />
                        }
                        price={"$40.00"}
                        title={"Product"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__icfqf)}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard___6IlFh
                        )}
                        image={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__kqX1Z)}
                            displayHeight={"100%"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            src={{
                              src: freddieMarriageUcfKyTanLuUnsplashjpgSug2Aysmy4PT9,
                              fullWidth: 640,
                              fullHeight: 427,
                              aspectRatio: undefined
                            }}
                          />
                        }
                        onSale={true}
                        price={"$100.00"}
                        title={"Product"}
                      />
                    </div>
                  </p.Stack>
                ) : null}
                {true ? (
                  <FeatureItem
                    data-plasmic-name={"featureItem"}
                    data-plasmic-override={overrides.featureItem}
                    className={classNames("__wab_instance", sty.featureItem)}
                  />
                ) : null}
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dvEoc)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__g19Vf
                      )}
                    >
                      {"Featured Products"}
                    </div>
                  </div>
                ) : null}
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__wEaO)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__xNlmz)}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__zr6G1
                        )}
                        price={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___2Tnb0
                            )}
                          >
                            {"$160.00"}
                          </div>
                        }
                        title={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jnLl8
                            )}
                          >
                            {"Designed Sofa"}
                          </div>
                        }
                        withReviews={true}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__klDpj)}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__jOA
                        )}
                        image={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__pt366)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            src={{
                              src: f2NTxTx2MaIc83Th,
                              fullWidth: 270,
                              fullHeight: 310,
                              aspectRatio: undefined
                            }}
                          />
                        }
                        price={"$200.00"}
                        title={"Dining Table"}
                        withReviews={true}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__hjKZa)}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard___1Eruk
                        )}
                        image={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img___16Tef)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            src={{
                              src: f3QkcmvqYxHP4IK,
                              fullWidth: 270,
                              fullHeight: 310,
                              aspectRatio: undefined
                            }}
                          />
                        }
                        price={"$100.00"}
                        title={"Chair and Table"}
                        withReviews={true}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__kfJsr)}
                    >
                      <ProductCard
                        className={classNames(
                          "__wab_instance",
                          sty.productCard__zV3WB
                        )}
                        image={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__yMOsP)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            src={{
                              src: f4SaIjz82E8CVBx,
                              fullWidth: 270,
                              fullHeight: 310,
                              aspectRatio: undefined
                            }}
                          />
                        }
                        price={"$299.00"}
                        title={"Modern Arm Chair"}
                        withReviews={true}
                      />
                    </div>
                  </p.Stack>
                ) : null}
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lmqlX)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uiM67
                      )}
                    >
                      {"Latest Blog"}
                    </div>
                  </div>
                ) : null}
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__rNbIn)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__p9Ckg)}
                    >
                      <BlogPost
                        className={classNames(
                          "__wab_instance",
                          sty.blogPost__ywyI5
                        )}
                        image={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__upc2F)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            src={{
                              src: b14B1JYr2A7Rzllu,
                              fullWidth: 370,
                              fullHeight: 250,
                              aspectRatio: undefined
                            }}
                          />
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__wd9A)}
                    >
                      <BlogPost
                        className={classNames(
                          "__wab_instance",
                          sty.blogPost__nunnP
                        )}
                        image={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img___69XfP)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            src={{
                              src: b2W7N7NGOmbXw1KV,
                              fullWidth: 370,
                              fullHeight: 250,
                              aspectRatio: undefined
                            }}
                          />
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__p1XVe)}
                    >
                      <BlogPost
                        className={classNames(
                          "__wab_instance",
                          sty.blogPost__qeNxJ
                        )}
                        image={
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img___6Ga3X)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            src={{
                              src: b3EKschWy364XeXy,
                              fullWidth: 370,
                              fullHeight: 250,
                              aspectRatio: undefined
                            }}
                          />
                        }
                      />
                    </div>
                  </p.Stack>
                ) : null}
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__dpKr)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__g5M7D)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"90px"}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__pqfrU)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"91px"}
                      src={{
                        src: imageNRu8G82XNgF0Pk,
                        fullWidth: 91,
                        fullHeight: 60,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__f0Nde)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"98px"}
                      src={{
                        src: kappaTrboBxmt9M7Ie5,
                        fullWidth: 98,
                        fullHeight: 60,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__dgVMz)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"124px"}
                      src={{
                        src: lacosteTEWbuNfm5Ff8Xp,
                        fullWidth: 124,
                        fullHeight: 60,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__juMqk)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"125px"}
                      src={{
                        src: levisXnOQSlkr9SjGe,
                        fullWidth: 125,
                        fullHeight: 60,
                        aspectRatio: undefined
                      }}
                    />
                  </p.Stack>
                ) : null}
                {true ? (
                  <Footer
                    className={classNames("__wab_instance", sty.footer__a8YCe)}
                  />
                ) : null}
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                data-plasmic-name={"bigPlants"}
                data-plasmic-override={overrides.bigPlants}
                hasGap={true}
                className={classNames(projectcss.all, sty.bigPlants)}
              >
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___9TaPg)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__nW6A
                      )}
                    >
                      {"Big plants"}
                    </h2>
                  </p.Stack>
                ) : null}
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__unwa)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__l4Ba2)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__tHeJ)}
                      displayHeight={
                        "270px /* plasmic-token: FrVxrO3xIVC8IA */"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: plant6JpgSmvOu1Xxq5VnGt,
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__cDmW6
                        )}
                      >
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__sDIf9)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <div
                      className={classNames(projectcss.all, sty.freeBox__am4NL)}
                    >
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__l1Frq
                        )}
                      >
                        {"Donec finibus"}
                      </a>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__domv
                        )}
                      >
                        {"bigplants"}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__uAl6N
                        )}
                      >
                        {"$100.00"}
                      </h5>
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__tjVev)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ndAu8)}
                      displayHeight={
                        "270px /* plasmic-token: FrVxrO3xIVC8IA */"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: plant1Jpg24LuZtbCwp7W2,
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nkIqo
                        )}
                      >
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__qvWyl)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <div
                      className={classNames(projectcss.all, sty.freeBox__aZlmY)}
                    >
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__zHeXw
                        )}
                      >
                        {"Nulla suscipit"}
                      </a>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tOmJs
                        )}
                      >
                        {"bigplants "}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__b2Soj
                        )}
                      >
                        {"$49.40 "}
                      </h5>
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__p7M5S)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__mRLh6)}
                      displayHeight={
                        "270px /* plasmic-token: FrVxrO3xIVC8IA */"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: plant7JpgYuSlZZhiiBuc0,
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__eu1U2
                        )}
                      >
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__wlfIp)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zpBr8)}
                    >
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__m6Vf
                        )}
                      >
                        {"Sed consectetur"}
                      </a>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__v0Qsc
                        )}
                      >
                        {"bigplants "}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__wuGDj
                        )}
                      >
                        {"$18.40 "}
                      </h5>
                    </div>
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__gjEs)}
                      displayHeight={
                        "270px /* plasmic-token: FrVxrO3xIVC8IA */"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: plant5JpgBQJxNrXugOtY,
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ayMhF
                        )}
                      >
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__cb6FI)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bn0K0)}
                    >
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__p0PpH
                        )}
                      >
                        {"Vestibulum eget"}
                      </a>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nwSJf
                        )}
                      >
                        {"bigplants "}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__dW7Bg
                        )}
                      >
                        {"$220.40 "}
                      </h5>
                    </div>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                data-plasmic-name={"cactuses"}
                data-plasmic-override={overrides.cactuses}
                hasGap={true}
                className={classNames(projectcss.all, sty.cactuses)}
              >
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___5YnmX)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2___4YN1M
                      )}
                    >
                      {"Cactuses"}
                    </h2>
                  </p.Stack>
                ) : null}
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__dFl8P)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__cw695)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ubTnN)}
                      displayHeight={
                        "270px /* plasmic-token: FrVxrO3xIVC8IA */"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: plant41JpgRLnicAZhoI7Gtg,
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rqre
                        )}
                      >
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__mts31)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <div
                      className={classNames(projectcss.all, sty.freeBox__t1GWc)}
                    >
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__yznBb
                        )}
                      >
                        {"Cras molestie"}
                      </a>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vhEiB
                        )}
                      >
                        {"cactuses "}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__oRm6L
                        )}
                      >
                        {"$24.99"}
                      </h5>
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__dDtgk)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__p3YsY)}
                      displayHeight={
                        "270px /* plasmic-token: FrVxrO3xIVC8IA */"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: plant31JpgRWGlkbLwKqsXk2,
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__reldm
                        )}
                      >
                        <Icon3Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___6ZKly
                          )}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <div
                      className={classNames(projectcss.all, sty.freeBox__n5Aer)}
                    >
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__u9YiP
                        )}
                      >
                        {"Curabitur eu tempor"}
                      </a>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zwAGa
                        )}
                      >
                        {"Cactuses"}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5___1Smn4
                        )}
                      >
                        {"$49.40 "}
                      </h5>
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__kdELx)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__tBdsC)}
                      displayHeight={
                        "270px /* plasmic-token: FrVxrO3xIVC8IA */"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: plant9Webp3TPkYmbEMcCrq,
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xPvz2
                        )}
                      >
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__f2Ls3)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <div
                      className={classNames(projectcss.all, sty.freeBox__tSpMu)}
                    >
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__f5Zl
                        )}
                      >
                        {"Fusce sagittis"}
                      </a>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__w5N4
                        )}
                      >
                        {"Fusce sagittis"}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__mLIu
                        )}
                      >
                        {"$49.40 "}
                      </h5>
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__ySZdk)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__qh9Vy)}
                      displayHeight={
                        "270px /* plasmic-token: FrVxrO3xIVC8IA */"
                      }
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: plant2WebpXdOep6UpMySuvS,
                        fullWidth: 400,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xdz2Y
                        )}
                      >
                        <Icon3Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___9GFzO
                          )}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wLtFd)}
                    >
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__aCArM
                        )}
                      >
                        {"Integer porta"}
                      </a>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__i52Gf
                        )}
                      >
                        {"Cactuses"}
                      </div>
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__r5Yz4
                        )}
                      >
                        {"$49.40 "}
                      </h5>
                    </div>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            ) : null}
            <Footer
              className={classNames("__wab_instance", sty.footer__qcOjA)}
            />
          </div>
        </div>
      </React.Fragment>
    </p.PlasmicPageGuard>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header3",
    "foreground2",
    "h3",
    "header",
    "header2",
    "featureItem",
    "bigPlants",
    "cactuses"
  ],

  header3: ["header3"],
  foreground2: ["foreground2", "h3"],
  h3: ["h3"],
  header: ["header", "header2", "featureItem"],
  header2: ["header2"],
  featureItem: ["featureItem"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProdottoBibita__ArgProps,
          internalVariantPropNames: PlasmicProdottoBibita__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicProdottoBibita__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProdottoBibita";
  } else {
    func.displayName = `PlasmicProdottoBibita.${nodeName}`;
  }
  return func;
}

export const PlasmicProdottoBibita = Object.assign(
  // Top-level PlasmicProdottoBibita renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header3: makeNodeComponent("header3"),
    foreground2: makeNodeComponent("foreground2"),
    h3: makeNodeComponent("h3"),
    header: makeNodeComponent("header"),
    header2: makeNodeComponent("header2"),
    featureItem: makeNodeComponent("featureItem"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    // Metadata about props expected for PlasmicProdottoBibita
    internalVariantProps: PlasmicProdottoBibita__VariantProps,
    internalArgProps: PlasmicProdottoBibita__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicProdottoBibita;
/* prettier-ignore-end */
